scan_filter_chain:
- name: range
  type: LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.2
    upper_threshold: 14.0
    lower_replacement_value: 15.0
    upper_replacement_value: 15.0